version: '3'
volumes:
  data:
services:
  db:
    container_name: db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nutrition-data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"